# Generated by Django 4.1.1 on 2022-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, verbose_name='Категория затрат')),
                ('type', models.IntegerField(choices=[(1, 'Доход'), (2, 'Расход')], verbose_name='Тип денежного движения')),
            ],
        ),
    ]
