# Generated by Django 4.1.1 on 2022-09-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whereismymoney', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(choices=[(0, 'Доход'), (1, 'Расход')], verbose_name='Тип денежного движения'),
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.FloatField(verbose_name='Сумма')),
                ('name', models.CharField(max_length=128, verbose_name='Пояснение')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whereismymoney.category')),
            ],
        ),
    ]
