# Generated by Django 4.1.1 on 2022-09-25 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whereismymoney', '0003_alter_pay_options_pay_date_alter_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
