# Generated by Django 4.1.1 on 2022-09-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whereismymoney', '0004_pay_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='user_id',
            new_name='user',
        ),
    ]
